<?php

declare(strict_types=1);

use Composer\Semver\VersionParser;

require_once '/app/.liminal/classmap.php';

$input = json_decode(file_get_contents('/app/.liminal/tmp/in.json'), true, 512, JSON_THROW_ON_ERROR);
$packages = $input['packages'] ?? [];
$vendorBase = '/app/vendor';
$psr4 = [];
$psr0 = [];
$classmap = [];
$files = [];
$installedJsonPath = '/app/vendor/composer/installed.json';
$installedPhpPath = '/app/vendor/composer/installed.php';

$join = static function (string $base, string $relative): string {
    $relative = str_replace('\\', '/', $relative);
    return rtrim($base, '/').'/'.ltrim($relative, '/');
};

$addAutoload = static function (array $autoload, string $base) use (
    &$psr4,
    &$psr0,
    &$classmap,
    &$files,
    $join
): void {
    foreach ($autoload['psr-4'] ?? [] as $prefix => $paths) {
        foreach ((array) $paths as $path) {
            $psr4[$prefix][] = $join($base, (string) $path);
        }
    }

    foreach ($autoload['psr-0'] ?? [] as $prefix => $paths) {
        foreach ((array) $paths as $path) {
            $psr0[$prefix][] = $join($base, (string) $path);
        }
    }

    foreach ((array) ($autoload['classmap'] ?? []) as $path) {
        $classmap = array_replace($classmap, liminal_scan_classmap($join($base, (string) $path)));
    }

    foreach ((array) ($autoload['files'] ?? []) as $path) {
        $file = $join($base, (string) $path);
        if (is_file($file)) {
            $files[] = $file;
        }
    }
};

$installedJson = file_exists($installedJsonPath)
    ? json_decode(file_get_contents($installedJsonPath), true, 512, JSON_THROW_ON_ERROR)
    : ['packages' => []];
$installedList = isset($installedJson['packages']) ? $installedJson['packages'] : $installedJson;
$installedByName = [];
foreach ($installedList as $index => $installedPackage) {
    if (isset($installedPackage['name'])) {
        $installedByName[$installedPackage['name']] = $index;
    }
}

$installedPhp = file_exists($installedPhpPath)
    ? require $installedPhpPath
    : ['root' => [], 'versions' => []];
$installedPhp['versions'] ??= [];
$parser = new VersionParser();

foreach ($packages as $name => $locked) {
    $packageBase = $vendorBase.'/'.$name;
    $composerPath = $packageBase.'/composer.json';
    if (!is_file($composerPath)) {
        throw new RuntimeException("Missing composer.json for dynamically installed package {$name}");
    }

    $composer = json_decode(file_get_contents($composerPath), true, 512, JSON_THROW_ON_ERROR);
    $addAutoload($composer['autoload'] ?? [], $packageBase);

    $prettyVersion = $locked['version'];
    try {
        $normalizedVersion = $locked['normalizedVersion'] ?? $parser->normalize($prettyVersion);
    } catch (UnexpectedValueException) {
        $normalizedVersion = $locked['normalizedVersion'] ?? $prettyVersion;
    }

    $jsonEntry = [
        'name' => $name,
        'version' => $prettyVersion,
        'version_normalized' => $normalizedVersion,
        'type' => $composer['type'] ?? 'library',
        'install-path' => '../'.$name,
        'autoload' => $composer['autoload'] ?? (object) [],
        'extra' => $composer['extra'] ?? (object) [],
    ];

    if (isset($installedByName[$name])) {
        $installedList[$installedByName[$name]] = array_replace(
            $installedList[$installedByName[$name]],
            $jsonEntry
        );
    } else {
        $installedByName[$name] = count($installedList);
        $installedList[] = $jsonEntry;
    }

    $installedPhp['versions'][$name] = [
        'pretty_version' => $prettyVersion,
        'version' => $normalizedVersion,
        'reference' => $locked['reference'] ?? null,
        'type' => $composer['type'] ?? 'library',
        'install_path' => $packageBase,
        'aliases' => [],
        'dev_requirement' => false,
    ];
}

// Root development autoloading remains useful for imported projects, but
// dependency autoload-dev sections are intentionally ignored.
$rootComposer = json_decode(file_get_contents('/app/composer.json'), true, 512, JSON_THROW_ON_ERROR);
$addAutoload($rootComposer['autoload-dev'] ?? [], '/app');
uksort($psr4, static fn(string $left, string $right): int => strlen($right) <=> strlen($left));
uksort($psr0, static fn(string $left, string $right): int => strlen($right) <=> strlen($left));

$autoloadCode = <<<'PHP'
<?php
// GENERATED BY LIMINAL — do not edit.
$psr4 = %s;
$psr0 = %s;
$classmap = %s;
$files = %s;

spl_autoload_register(function (string $class) use ($psr4, $psr0, $classmap): void {
    if (isset($classmap[$class])) {
        require $classmap[$class];
        return;
    }

    foreach ($psr4 as $prefix => $directories) {
        if (strncmp($prefix, $class, strlen($prefix)) !== 0) {
            continue;
        }
        $relative = str_replace('\\', '/', substr($class, strlen($prefix))).'.php';
        foreach ($directories as $directory) {
            $file = rtrim($directory, '/').'/'.$relative;
            if (is_file($file)) {
                require $file;
                return;
            }
        }
    }

    foreach ($psr0 as $prefix => $directories) {
        if (strncmp($prefix, $class, strlen($prefix)) !== 0) {
            continue;
        }
        $relative = str_replace(['\\', '_'], '/', $class).'.php';
        foreach ($directories as $directory) {
            $file = rtrim($directory, '/').'/'.$relative;
            if (is_file($file)) {
                require $file;
                return;
            }
        }
    }
}, true, false);

foreach ($files as $file) {
    require_once $file;
}
PHP;

file_put_contents('/app/.liminal/autoload.php', sprintf(
    $autoloadCode,
    var_export($psr4, true),
    var_export($psr0, true),
    var_export($classmap, true),
    var_export(array_values(array_unique($files)), true),
));

if (isset($installedJson['packages'])) {
    $installedJson['packages'] = array_values($installedList);
} else {
    $installedJson = array_values($installedList);
}
file_put_contents(
    $installedJsonPath,
    json_encode($installedJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)
);
file_put_contents($installedPhpPath, "<?php\n\nreturn ".var_export($installedPhp, true).";\n");

if (class_exists(Composer\InstalledVersions::class)) {
    Composer\InstalledVersions::reload($installedPhp);
}

echo json_encode([
    'packages' => count($packages),
    'psr4' => count($psr4),
    'psr0' => count($psr0),
    'classmap' => count($classmap),
    'files' => count($files),
], JSON_THROW_ON_ERROR);
